wallpaper {
    monitor = DP-1
    path = /home/carter/.config/backgrounds/background.jpg
    fit_mode = cover
}

wallpaper {
    monitor = DP-2
    path = /home/carter/.config/backgrounds/background.jpg
    fit_mode = cover
}
